# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7fd720c1a0040ae9d9ddb40847e7ead7fd1899f023d96426d5392d9a1f805eabcb35e5368769ae876a3ba2b0821aae043666c4d2f109d47b848a2218abc0482

test:
  secret_key_base: 825bc1fc7e4cf7f9ad49227af2cdff11df288198324910966c697aee6dfb83edc2249f8250a58f5865c29959a0540dd6761a1ed13e9b2bd0b5408cfb4e1d57cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
